apiVersion: v1
kind: Service
metadata: 
  name: {{ .Chart.Name }}-server
  labels:
    project: {{ .Chart.Name }}
    name: {{ .Chart.Name }}-server
    app: {{ .Chart.Name }}-server
    githash: {{ .Values.deploy.imageTag }}
spec:
  # Aladdin will fill this in as NodePort which will expose itself to things outside of the cluster
  # This is to highlight difference between public and private service types, and to only use
  # public service types when it truly should be public
  type: {{ .Values.service.publicServiceType | quote }}
  ports:
    - name: http
    # Expose the nginx port if we are using it, otherwise expose the uwsgi port
{{ if .Values.app.nginx.use }}
      port: {{ .Values.app.nginx.port }}
{{ else }}
      port: {{ .Values.app.port }}
{{ end }}
  selector:
    # Get the aladdin-demo-server deployment configuration from sever/deploy.yaml
    name: {{ .Chart.Name }}-server
