# Values here will overwrite values.yaml defaults. These values are used when deploying locally to minikube
# Application configuration
app:
  # default to the python app port
  port: 7892
  nginx:
    use: true
    port: 8001

deploy:
  # number of seconds for the containers to perform a graceful shutdown, after which it is voilently terminated
  terminationGracePeriod: 50
  replicas: 1

redis:
  create: true
  port: 6379
  containerPort: 6379

elasticsearch:
  create: true
  populate: true
  # 1000 is the uid of the first non-root user created, in our case that is the elasticsearch user
  id: 1000
  port: 9200
  containerPort: 9200
  storage: 1Gi
