# Application configuration
app:
  # default to the python app port
  port: 7892
  nginx:
    useNginx: true
    port: 8001

deploy:
  terminationGracePeriod: 50
  replicas: 1

redis:
  createRedis: true
  port: 6379
  containerPort: 6379
