# This is the default values file, which should be treated as a template. Values should only be defined
# here if they are shared accross all non-local environments. However, list and comment on all potential values.

app:
  uwsgi:
    port: 8000
    # processes: 16
  nginx:
    use: true
    port: 80
    httpPort: 80
    httpsPort: 443

deploy:
  # number of seconds for the containers to perform a graceful shutdown, after which it is voilently terminated
  terminationGracePeriod: 50
  replicas: 1

env:
  MESSAGE: 'aladdin-demo message'
