apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    name: {{ .Chart.Name }}
spec:
  replicas: {{.Values.deploy.replicas}}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        deploymentconfig: {{ .Chart.Name }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.deploy.terminationGracePeriod }}
      containers:
      # aladdin-demo falcon app
      - name: aladdin-demo
        image: aladdin-demo:local
        workingDir: /home/aladdin-demo 
        ports:
        - containerPort: {{ .Values.app.port }}
          protocol: TCP
        envFrom:
          # Load the data from configMap into the runtime environment
          # This allows us to use os.environ["KEY"] to look up variables
          - configMapRef:
              name: {{ .Chart.Name }}-config
{{ if .Values.app.nginx.useNginx }}
      # nginx container
      - name: {{ .Chart.Name }}-nginx
        image: {{ .Chart.Name }}-nginx:local
        ports: 
          - containerPort: {{ .Values.app.nginx.port }}
            protocol: TCP
{{ end }}