apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: db
  labels:
    project: {{ .Chart.Name }}
    name: {{ .Chart.Name }}-elasticsearch
    app: {{ .Chart.Name }}-elasticsearch
    githash: {{.Values.deploy.imageTag}}
spec:
  selector:
    matchLabels:
      name: {{ .Chart.Name }}-elasticsearch
  # The name of the service that governs this StatefulSet, must exist before the StatefulSet    
  serviceName: {{ .Chart.Name }}-elasticsearch
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        name: {{ .Chart.Name }}-elasticsearch # has to match .spec.selector.matchLabels
    spec:
      # This initContainer increases the vm.max_map_count to satisfy the bootstrap checks of elasticsearch
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      terminationGracePeriodSeconds: 10
      containers:
      - name: {{ .Chart.Name }}-elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
        ports:
        - containerPort: {{ .Values.elasticsearch.containerPort }}
        volumeMounts:
        - name: {{ .Chart.Name }}-elasticsearch
          # Volume mounts will override the mountPath, which in this case has a lot of other useful
          # things in it, we only want to mount elasticsearch.yml 
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          # Configmaps are lists of key-value pairs, and we only need one of the keys, so we
          # specify that with a subpath 
          subPath: elasticsearch.yml
        - name: storage
          mountPath: /data
      volumes:
        - name: {{ .Chart.Name }}-elasticsearch
          configMap:
            name: {{ .Chart.Name }}-elasticsearch
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
