apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-elasticsearch
  labels:
    project: {{ .Chart.Name }}
    name: {{ .Chart.Name }}-elasticsearch
    app: {{ .Chart.Name }}-elasticsearch
    githash: {{.Values.deploy.imageTag}}
spec:
{{ if .Values.elasticsearch.create }}
  type: {{ .Values.service.privateServiceType | quote }}
  selector:
    name: {{ .Chart.Name }}-elasticsearch
  ports:
  - name: elasticsearch
    protocol: TCP
    port: {{ .Values.elasticsearch.port }}
    targetPort: elasticsearch
{{ else }}
  type: ExternalName
  externalName: {{ .Values.elasticsearch.host }}
{{ end }} # /elasticsearch.create
