apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    name: {{ .Chart.Name }}
spec:
  replicas: {{.Values.deploy.replicas}}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        deploymentconfig: {{ .Chart.Name }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.deploy.terminationGracePeriod }}
      containers:
      # falcon app container
      - name: {{ .Chart.Name }}
        image: {{ .Chart.Name }}:local
        workingDir: /home/{{ .Chart.Name}} 
        ports:
        - containerPort: {{ .Values.app.port }}
          protocol: TCP
        # Mount the configuration file into the docker container
        volumeMounts:
          - mountPath: /config/
            name: {{ .Chart.Name }}-uwsgi-config
        envFrom:
          # Load the data from configMap into the runtime environment
          # This allows us to use os.environ["KEY"] to look up variables
          - configMapRef:
              name: {{ .Chart.Name }}-config
{{ if .Values.app.nginx.useNginx }}
      # nginx container
      - name: {{ .Chart.Name }}-nginx
        image: nginx:1.12-alpine
        ports: 
          - containerPort: {{ .Values.app.nginx.port }}
            protocol: TCP
        volumeMounts:
          - mountPath: /etc/nginx/
            name: {{ .Chart.Name }}-nginx-config
{{ end }}
        envFrom:
          - configMapRef:
              name: {{ .Chart.Name }}-config
      # Specify volumes
      volumes:
        - name: {{ .Chart.Name }}-nginx-config
          configMap:
            name: {{ .Chart.Name }}-nginx-config
        - name: {{ .Chart.Name }}-uwsgi-config
          configMap:
            name: {{ .Chart.Name }}-uwsgi-config
