apiVerson: v1
kind: ConfigMap
metadata: 
  name: {{ .Chart.Name }}
  labels:
    project: {{ .Chart.Name }}
    app: {{ .Chart.Name }}
    name: {{ .Chart.Name }}
    githash: {{ .Values.deploy.imageTag }}
# Create key - value entries in the data map that other files can look up
# Load them into the environment by using configMapRef in the deploy.yaml file
data:
  REDIS_HOST: {{ .Chart.Name }}-redis
  REDIS_PORT: {{ .Values.redis.port | quote }}
  REDIS_CREATE: {{ .Values.redis.create | quote }}
