apiVersion: v1
kind: Service
metadata: 
  name: {{ .Chart.Name }}
  labels:
    name: {{ .Chart.Name }}
    app: {{ .Chart.Name }}
spec:
  type: NodePort
  ports:
    - name: http
    # Expose the nginx port if we are using it, otherwise expose the uwsgi port
{{ if .Values.app.nginx.useNginx }}
      port: {{ .Values.app.nginx.port }}
{{ else }}
      port: {{ .Values.app.port }}
{{ end }}
  selector:
    deploymentconfig: {{ .Chart.Name }}
