{{if .Values.redis.create }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-redis
  labels:
    project: {{ .Chart.Name }}
    name: {{ .Chart.Name }}-redis
    app: {{ .Chart.Name }}-redis
    githash: {{ .Values.deploy.imageTag }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        project: {{ .Chart.Name }}
        name: {{ .Chart.Name }}-redis
        app: {{ .Chart.Name }}-redis
        githash: {{ .Values.deploy.imageTag }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-redis
        image: redis:2.8
        ports:
        - containerPort: {{ .Values.redis.containerPort }}
          protocol: TCP
{{end}}
