{{if .Values.createRedis }}
apiVersion: v1
kind: Service
metadata:
  name: aladdin-demo-redis
  labels:
    name: aladdin-demo-redis
    app: aladdin-demo-redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: aladdin-demo-redis
{{end}}