apiVerson: v1
kind: ConfigMap
metadata: 
  name: {{ .Chart.Name }}
  labels:
    project: {{ .Chart.Name }}
    name: {{ .Chart.Name }}
    app: {{ .Chart.Name }}
# Create key - value entries in the data map that other files can look up
data:
  REDIS_HOST: {{ .Chart.Name }}-redis
  REDIS_PORT: {{ .Values.redis.port | quote }}

---
# ConfigMap for nginx
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-nginx-config
data:
  # desired name for the file
  nginx.conf: {{ include "nginx-config" . | quote }}

---
# ConfigMap for uwsgi
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-uwsgi-config
data:
  uwsgi.yaml: {{ include "uwsgi-config" . | quote }}
