apiVerson: v1
kind: ConfigMap
metadata: 
  name: {{ .Chart.Name }}-config
  labels:
    project: {{ .Chart.Name }}
    name: {{ .Chart.Name }}-config
    app: {{ .Chart.Name }}
# Create key - value entries in the data map that other files can look up
data:
  REDIS_HOST: {{ .Chart.Name }}-redis
  REDIS_PORT: {{ .Values.redis.port | quote }}
  NGINX_PORT: {{ .Values.app.nginx.port | quote }}
  UWSGI_PORT: {{ .Values.app.port | quote }}

